#**Mathematics Calculation of Singular Value Decomposition (SVD)**

This work is about simple example of mathematics computation of Singular Values Decomposition (SVD). The sample question is obtained from <a href="https://www.d.umn.edu/~mhampton/m4326svd_example.pdf">here</a>

In [1]:
import numpy as np
import pandas as pd
import math
from sympy import symbols, Matrix

In [2]:
A = np.array([[3,2,2],[2,3,-2]]) 
print('Array A is:')
print(A)

Array A is:
[[ 3  2  2]
 [ 2  3 -2]]


To compute the singular values, σi, have to determine the eigenvalues of AAT.

In [3]:
AT = A.transpose()
print('Transpose of A is:')
print(AT)

Transpose of A is:
[[ 3  2]
 [ 2  3]
 [ 2 -2]]


In [4]:
AAT = np.dot(A,AT)
print('AAT is:')
print(AAT)

AAT is:
[[17  8]
 [ 8 17]]


For ATA

In [5]:
ATA = np.dot(AT,A)
print('ATA is:')
print(ATA)

ATA is:
[[13 12  2]
 [12 13 -2]
 [ 2 -2  8]]


Then compute the characteristic polynomial for det(AAT − λI) by using **sympy** library.

In [20]:
from sympy import symbols, Matrix

l, at, i = symbols(['Lambda', 'AT', 'I']) # Turn characters into symbolic variables
m = Matrix([[17-l, 8], [8, 17-l]]) # Define the matrix
print(m.det()) # Print its determinant

(-Lambda + 17)**2 - 64


Obtained from above expression, we can write it as

`-Lambda**2 -34 Lambda + 225`

Determine the roots which is known as eigenvectors.

In [23]:
coeff = [1,-34, 225]
r = np.roots(coeff)
print('The eigenvalues are:')
print(r)

The eigenvalues are:
[25.  9.]
