#**Mathematics Calculation of Singular Value Decomposition (SVD)**

This work is about simple example of mathematics computation of Singular Values Decomposition (SVD). The sample question is obtained from <a href="https://www.d.umn.edu/~mhampton/m4326svd_example.pdf">here</a>

In [1]:
import numpy as np
import pandas as pd
import math
from sympy import symbols, Matrix

In [2]:
A = np.array([[3,2,2],[2,3,-2]]) 
print('Array A is:')
print(A)

Array A is:
[[ 3  2  2]
 [ 2  3 -2]]


To compute the singular values, σi, have to determine the eigenvalues of AAT.

In [3]:
AT = A.transpose()
print('Transpose of A is:')
print(AT)

Transpose of A is:
[[ 3  2]
 [ 2  3]
 [ 2 -2]]


In [4]:
AAT = np.dot(A,AT)
print('AAT is:')
print(AAT)

AAT is:
[[17  8]
 [ 8 17]]


For ATA

In [5]:
ATA = np.dot(AT,A)
print('ATA is:')
print(ATA)

ATA is:
[[13 12  2]
 [12 13 -2]
 [ 2 -2  8]]


Then compute the characteristic polynomial for det(AAT − λI) by using **sympy** library.

In [6]:
from sympy import symbols, Matrix

l, at, i = symbols(['Lambda', 'AT', 'I']) # Turn characters into symbolic variables
m = Matrix([[17-l, 8], [8, 17-l]]) # Define the matrix
print(m.det()) # Print its determinant

(-Lambda + 17)**2 - 64


Obtained from above expression, we can write it as

`-Lambda**2 -34 Lambda + 225`

Determine the roots which is known as eigenvalues. The singular values are the square root of positive eigenvalues.

In [7]:
coeff = [1,-34, 225]
r = np.roots(coeff)
print('The eigenvalues for AAT are:')
print(r)

The eigenvalues for AAT are:
[25.  9.]


In [8]:
sv = np.sqrt(r)
print('The singular values are:')
print(sv)

The singular values are:
[5. 3.]


Let Lambda1, λ1 be 25,

(AAT − λI)v = 0

Then find out v

In [9]:
# Let lambda1 be 25

j1 = AAT - np.array([[25,0],[0,25]])
j1

array([[-8,  8],
       [ 8, -8]])

As a result, the v is [1,1]. Next, determine the magnitude of v, by square root of (1^2 + 1^2) , which is equal to 1.4142135.

In [10]:
# unit eigenvector
v1 = np.array([1/1.4142135, 1/1.4142135])
v1

array([0.70710681, 0.70710681])

In [11]:
# Let lambda1 be 25

j2 = AAT - np.array([[9,0],[0,9]])
j2

array([[8, 8],
       [8, 8]])

As a result, the vector is [1,-1]. Next, determine the magnitude of v, by square root of (1^2 + -1^2) , which is equal to 1.4142135.

In [12]:
# unit eigenvector
v2 = np.array([1/1.4142135, -1/1.4142135])
v2

array([ 0.70710681, -0.70710681])

The robust library, Numpy has provide function to compute the eigenvalues and right eigenvectors of a square array easily. More details can refer to [here](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html).

In [13]:
from numpy import linalg as LA

w_AAT, v_AAT = LA.eig(AAT)

In [14]:
w_AAT

array([25.,  9.])

In [15]:
# Eigenvectors of AAT
v_AAT

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

Now check the eigenvalue for ATA

In [16]:
m2 = Matrix([[13-l,12, 2], [12, 13-l, -2], [2,-2,8-l]]) # Define the matrix
print(m2.det()) # Print its determinant

152*Lambda + (-Lambda + 8)*(-Lambda + 13)**2 - 1352


By find out the coefficient of above polynomial equation, we can get the roots are 25 and 9. Same like method used in above to find out the eigenvectors.

In [17]:
# Let lambda1 be 25

k1 = ATA - np.array([[25,0, 0],[0,25,0], [0,0,25]])
k1

array([[-12,  12,   2],
       [ 12, -12,  -2],
       [  2,  -2, -17]])

After row-reduction, <br>
[ 1 	 -1 	 0]<br>
[ 0 	  0 	 1]<br>
[ 0 	  0 	 0]<br>

From matrix above, using Av = λv to determine the eigenvector, v

As a result, the eigenvector is [1,1,0], we can determine the unit vector and normalized vector.

In [18]:
eigen_v1 = np.array([1,1,0])
print('Eigenvector is ', eigen_v1)

# magnitude of vector
mag_k1 = np.linalg.norm(eigen_v1)
print('magnitude of the vector is:',mag_k1)
norm_eigen_v1 = eigen_v1 / mag_k1
print('normalized eigenvector is:', norm_eigen_v1)

Eigenvector is  [1 1 0]
magnitude of the vector is: 1.4142135623730951
normalized eigenvector is: [0.70710678 0.70710678 0.        ]


In [19]:
# Let lambda1 be 9

k2 = ATA - np.array([[9,0, 0],[0,9,0], [0,0,9]])
k2

array([[ 4, 12,  2],
       [12,  4, -2],
       [ 2, -2, -1]])

After row-reduction, <br>
[ 1 	 0 	 -1/4]<br>
[ 0 	  1 	 1/4]<br>
[ 0 	  0 	 0]<br>

From matrix above, using Av = λv to determine the eigenvector, v

As a result, the eigenvector is [1,-1,4], we can determine the unit vector and normalized vector.

In [20]:
eigen_v2 = np.array([1,-1,4])
print('Eigenvector is ', eigen_v2)

# magnitude of vector
mag_k2 = np.linalg.norm(eigen_v2)
print('magnitude of the vector is:',mag_k2)
norm_eigen_v2 = eigen_v2 / mag_k2
print('normalized eigenvector is:', norm_eigen_v2)

Eigenvector is  [ 1 -1  4]
magnitude of the vector is: 4.242640687119285
normalized eigenvector is: [ 0.23570226 -0.23570226  0.94280904]


In [21]:
ATA

array([[13, 12,  2],
       [12, 13, -2],
       [ 2, -2,  8]])

After row-reduction, <br>
[ 1 0 2] <br>
[ 0 1 -2] <br>
[ 0 0 0] <br>

From matrix above, using Av = λv to determine the eigenvector, v

As a result, the eigenvector is [2,-2,1], we can determine the unit vector and normalized vector.

In [22]:
eigen_v3 = np.array([2,-2,1])
print('Eigenvector is ', eigen_v3)

# magnitude of vector
mag_k3 = np.linalg.norm(eigen_v3)
print('magnitude of the vector is:',mag_k3)
norm_eigen_v3 = eigen_v3 / mag_k3
print('normalized eigenvector is:', norm_eigen_v3)

Eigenvector is  [ 2 -2  1]
magnitude of the vector is: 3.0
normalized eigenvector is: [ 0.66666667 -0.66666667  0.33333333]


Thus, we can write as in form

A = UΣVT

Σ is <br>
[5 0 0] <br>
[0 3 0]<br>

VT is <br>
[0.70710678, 0.70710678, 0] <br>
[0.23570226, -0.23570226,  0.94280904] <br>
[0.66666667, -0.66666667,  0.33333333] <br>

We can find the left singular vector, U by using σui = Avi

In [23]:
VT = np.array([[0.70710678, 0.70710678, 0],[0.23570226, -0.23570226, 0.94280904],[0.66666667, -0.66666667, 0.33333333]])
singular_vec = np.array([[5,0,0],[0,3,0]])

In [36]:
u1 = np.dot(A, norm_eigen_v1) * 1/5
u2 = np.dot(A, norm_eigen_v2) * 1/3

U = np.vstack((u1,u2))
U

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

# **Checking**
Now we have the full expression of SVD, and A = UΣVT

To verify, we can compute the right side part and check if it is equal to left part, A.

In [38]:
m  = np.dot(U,singular_vec)
np.dot(m, VT)

array([[ 2.99999999,  2.        ,  2.        ],
       [ 2.        ,  2.99999999, -2.        ]])

In [39]:
A

array([[ 3,  2,  2],
       [ 2,  3, -2]])

**It is correct!**

How about using Numpy library tools?

In [ ]:
w_ATA, v_ATA = LA.eig(ATA)
print('Eigenvalues for ATA is:')
print(w_ATA)
print('Eigenvector Matrix of ATA is:')
print(v_ATA)
transposed_v_ATA = v_ATA.transpose()
print('Eigenvector Matrix of ATA is:')
print(transposed_v_ATA)

Eigenvalues for ATA is:
[2.5000000e+01 5.0324328e-15 9.0000000e+00]
Eigenvector Matrix of ATA is:
[[-7.07106781e-01 -6.66666667e-01  2.35702260e-01]
 [-7.07106781e-01  6.66666667e-01 -2.35702260e-01]
 [-4.59701721e-17  3.33333333e-01  9.42809042e-01]]
Eigenvector Matrix of ATA is:
[[-7.07106781e-01 -7.07106781e-01 -4.59701721e-17]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]
 [ 2.35702260e-01 -2.35702260e-01  9.42809042e-01]]
